name: Generate Favicon

on:
  workflow_dispatch: # supaya bisa dijalankan manual dari GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create src directory and empty favicon.svg
        run: |
          mkdir -p src
          touch src/favicon.svg

      - name: Download avatar SVG using wget
        run: |
          wget -O src/favicon.svg "https://api.dicebear.com/9.x/bottts/svg?seed=Muhammad%20Riduwan%20Khafidi"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "🔧 Generate fresh favicon with Dicebear bottts"
          git push origin main
